experiment:
  name: "model-comparison"

  compute:
    type: "foundry"
    azure_ai_project: "https://foundry-evee-ko9z2s7c.services.ai.azure.com/api/projects/foundry-project-evee-ko9z2s7c"

  targets:
    - name: "model_compare"
      type: "azure_ai_model"
      deployment_name: ["gpt-4.1-mini", "gpt-4.1"]
      connection_name: "default"
      args:
        - temperature: [0.3, 0.9]

  dataset:
    name: "qa_data"
    type: "jsonl"
    args:
      data_path: "demo/data/data.jsonl"

  evaluators:
    - name: "relevance"
      mapping:
        query: "dataset.question"
        response: "model.answer"
    - name: "coherence"
      mapping:
        query: "dataset.question"
        response: "model.answer"
    - name: "conciseness"
      mapping:
        response: "model.answer"

  connections:
    default:
      azure_endpoint: "https://foundry-evee-ko9z2s7c.cognitiveservices.azure.com/"
      azure_deployment: "gpt-4.1-mini"
